#!/bin/sh
set -e

sed -i 's;http://repo.antixlinux.com;http://iso.mxrepo.com/antix;g' /etc/apt/sources.list.d/antix.list
sed -i 's;http://antix.daveserver.info;http://iso.mxrepo.com/antix;g' /etc/apt/sources.list.d/antix.list
